# Generated by Django 4.2.7 on 2023-11-15 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadKunUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('image', models.ImageField(upload_to='kun-uz/', verbose_name='Image')),
                ('set_data', models.DateField(blank=True, null=True, verbose_name='Set Data')),
                ('info', models.TextField(verbose_name='Info')),
            ],
        ),
        migrations.CreateModel(
            name='ThreeInfoUnder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('image', models.ImageField(upload_to='three-kun-uz/', verbose_name='Image')),
                ('set_data', models.DateField(blank=True, null=True, verbose_name='Set Data')),
                ('info', models.TextField(verbose_name='Info')),
            ],
        ),
        migrations.CreateModel(
            name='TodayNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('set_data', models.DateField(blank=True, null=True, verbose_name='Set Data')),
                ('info', models.TextField(verbose_name='Info')),
                ('image', models.ImageField(blank=True, upload_to='today-news/', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='UnderKunUz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('image', models.ImageField(upload_to='under-kun-uz/', verbose_name='Image')),
                ('set_data', models.DateField(blank=True, null=True, verbose_name='Set Data')),
                ('info', models.TextField(verbose_name='Info')),
            ],
        ),
        migrations.CreateModel(
            name='InternalMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Title')),
                ('set_data', models.DateField(blank=True, null=True, verbose_name='Set Data')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('info', models.TextField(verbose_name='Info')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temp.headkunuz')),
            ],
        ),
    ]
