# Generated by Django 4.2.7 on 2023-11-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threeinfounder',
            name='url',
            field=models.URLField(default='TodayNews', verbose_name='Urls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todaynews',
            name='url',
            field=models.URLField(default='UnderKunUz', verbose_name='Urls'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='underkunuz',
            name='url',
            field=models.URLField(default='ThreeInfoUnder', verbose_name='Urls'),
            preserve_default=False,
        ),
    ]
